### ISSUE TITLE
Deployment TODO

### ISSUE THREAD

**Issue by klauer** [pcdshub/solid-attenuator#41]
- [x] Add entry in IOC manager
- [x] Merge https://github.com/pcdshub/pcdsdevices/pull/489
- [x] Add happi entry
- [x] Fix #40 or at least make people aware of it

IOC start: `/reg/g/pcds/epics-dev/klauer/hxr-attenuator/ioc-satt-dev/iocBoot/st.cmd`

**Comment by klauer** [comment]
All the basics are done 👏
